// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingOperation.proto

package grpc.smartWarehouse.pickingOperations;

public interface BinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pickingOperations.BinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bin = 1;</code>
   */
  java.lang.String getBin();
  /**
   * <code>string bin = 1;</code>
   */
  com.google.protobuf.ByteString
      getBinBytes();
}
