// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingOperation.proto

package grpc.smartWarehouse.pickingOperations;

public interface BinRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pickingOperations.BinRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sku = 1;</code>
   */
  java.lang.String getSku();
  /**
   * <code>string sku = 1;</code>
   */
  com.google.protobuf.ByteString
      getSkuBytes();

  /**
   * <code>string productName = 2;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();
}
