// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingOperation.proto

package grpc.smartWarehouse.pickingOperations;

/**
 * Protobuf type {@code pickingOperations.PickResponse}
 */
public  final class PickResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pickingOperations.PickResponse)
    PickResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PickResponse.newBuilder() to construct.
  private PickResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PickResponse() {
    resultMessage_ = "";
    pickId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PickResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            resultMessage_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            pickId_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.smartWarehouse.pickingOperations.PickingOperationServiceProto.internal_static_pickingOperations_PickResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.smartWarehouse.pickingOperations.PickingOperationServiceProto.internal_static_pickingOperations_PickResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.smartWarehouse.pickingOperations.PickResponse.class, grpc.smartWarehouse.pickingOperations.PickResponse.Builder.class);
  }

  public static final int RESULTMESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object resultMessage_;
  /**
   * <code>string resultMessage = 1;</code>
   */
  public java.lang.String getResultMessage() {
    java.lang.Object ref = resultMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resultMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string resultMessage = 1;</code>
   */
  public com.google.protobuf.ByteString
      getResultMessageBytes() {
    java.lang.Object ref = resultMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resultMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PICKID_FIELD_NUMBER = 2;
  private volatile java.lang.Object pickId_;
  /**
   * <code>string pickId = 2;</code>
   */
  public java.lang.String getPickId() {
    java.lang.Object ref = pickId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pickId_ = s;
      return s;
    }
  }
  /**
   * <code>string pickId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPickIdBytes() {
    java.lang.Object ref = pickId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pickId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getResultMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resultMessage_);
    }
    if (!getPickIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pickId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getResultMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resultMessage_);
    }
    if (!getPickIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pickId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.smartWarehouse.pickingOperations.PickResponse)) {
      return super.equals(obj);
    }
    grpc.smartWarehouse.pickingOperations.PickResponse other = (grpc.smartWarehouse.pickingOperations.PickResponse) obj;

    boolean result = true;
    result = result && getResultMessage()
        .equals(other.getResultMessage());
    result = result && getPickId()
        .equals(other.getPickId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULTMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getResultMessage().hashCode();
    hash = (37 * hash) + PICKID_FIELD_NUMBER;
    hash = (53 * hash) + getPickId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.smartWarehouse.pickingOperations.PickResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.smartWarehouse.pickingOperations.PickResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.smartWarehouse.pickingOperations.PickResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pickingOperations.PickResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pickingOperations.PickResponse)
      grpc.smartWarehouse.pickingOperations.PickResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.smartWarehouse.pickingOperations.PickingOperationServiceProto.internal_static_pickingOperations_PickResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.smartWarehouse.pickingOperations.PickingOperationServiceProto.internal_static_pickingOperations_PickResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.smartWarehouse.pickingOperations.PickResponse.class, grpc.smartWarehouse.pickingOperations.PickResponse.Builder.class);
    }

    // Construct using grpc.smartWarehouse.pickingOperations.PickResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      resultMessage_ = "";

      pickId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.smartWarehouse.pickingOperations.PickingOperationServiceProto.internal_static_pickingOperations_PickResponse_descriptor;
    }

    @java.lang.Override
    public grpc.smartWarehouse.pickingOperations.PickResponse getDefaultInstanceForType() {
      return grpc.smartWarehouse.pickingOperations.PickResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.smartWarehouse.pickingOperations.PickResponse build() {
      grpc.smartWarehouse.pickingOperations.PickResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.smartWarehouse.pickingOperations.PickResponse buildPartial() {
      grpc.smartWarehouse.pickingOperations.PickResponse result = new grpc.smartWarehouse.pickingOperations.PickResponse(this);
      result.resultMessage_ = resultMessage_;
      result.pickId_ = pickId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.smartWarehouse.pickingOperations.PickResponse) {
        return mergeFrom((grpc.smartWarehouse.pickingOperations.PickResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.smartWarehouse.pickingOperations.PickResponse other) {
      if (other == grpc.smartWarehouse.pickingOperations.PickResponse.getDefaultInstance()) return this;
      if (!other.getResultMessage().isEmpty()) {
        resultMessage_ = other.resultMessage_;
        onChanged();
      }
      if (!other.getPickId().isEmpty()) {
        pickId_ = other.pickId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.smartWarehouse.pickingOperations.PickResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.smartWarehouse.pickingOperations.PickResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object resultMessage_ = "";
    /**
     * <code>string resultMessage = 1;</code>
     */
    public java.lang.String getResultMessage() {
      java.lang.Object ref = resultMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resultMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultMessageBytes() {
      java.lang.Object ref = resultMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resultMessage = 1;</code>
     */
    public Builder setResultMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resultMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string resultMessage = 1;</code>
     */
    public Builder clearResultMessage() {
      
      resultMessage_ = getDefaultInstance().getResultMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string resultMessage = 1;</code>
     */
    public Builder setResultMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resultMessage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pickId_ = "";
    /**
     * <code>string pickId = 2;</code>
     */
    public java.lang.String getPickId() {
      java.lang.Object ref = pickId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pickId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pickId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPickIdBytes() {
      java.lang.Object ref = pickId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pickId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pickId = 2;</code>
     */
    public Builder setPickId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pickId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pickId = 2;</code>
     */
    public Builder clearPickId() {
      
      pickId_ = getDefaultInstance().getPickId();
      onChanged();
      return this;
    }
    /**
     * <code>string pickId = 2;</code>
     */
    public Builder setPickIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pickId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pickingOperations.PickResponse)
  }

  // @@protoc_insertion_point(class_scope:pickingOperations.PickResponse)
  private static final grpc.smartWarehouse.pickingOperations.PickResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.smartWarehouse.pickingOperations.PickResponse();
  }

  public static grpc.smartWarehouse.pickingOperations.PickResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PickResponse>
      PARSER = new com.google.protobuf.AbstractParser<PickResponse>() {
    @java.lang.Override
    public PickResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PickResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PickResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PickResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.smartWarehouse.pickingOperations.PickResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

