// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingOperation.proto

package grpc.smartWarehouse.pickingOperations;

public final class PickingOperationServiceProto {
  private PickingOperationServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pickingOperations_BinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pickingOperations_BinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pickingOperations_BinResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pickingOperations_BinResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pickingOperations_PickRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pickingOperations_PickRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pickingOperations_PickResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pickingOperations_PickResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026PickingOperation.proto\022\021pickingOperati" +
      "ons\".\n\nBinRequest\022\013\n\003sku\030\001 \001(\t\022\023\n\013produc" +
      "tName\030\002 \001(\t\"\032\n\013BinResponse\022\013\n\003bin\030\001 \001(\t\"" +
      "A\n\013PickRequest\022\013\n\003bin\030\001 \001(\t\022\023\n\013productNa" +
      "me\030\002 \001(\t\022\020\n\010quantity\030\003 \001(\005\"5\n\014PickRespon" +
      "se\022\025\n\rresultMessage\030\001 \001(\t\022\016\n\006pickId\030\002 \001(" +
      "\t2\246\001\n\007Picking\022I\n\006getBin\022\035.pickingOperati" +
      "ons.BinRequest\032\036.pickingOperations.BinRe" +
      "sponse\"\000\022P\n\013pickProduct\022\036.pickingOperati" +
      "ons.PickRequest\032\037.pickingOperations.Pick" +
      "Response\"\000BG\n%grpc.smartWarehouse.pickin" +
      "gOperationsB\034PickingOperationServiceProt" +
      "oP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pickingOperations_BinRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pickingOperations_BinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pickingOperations_BinRequest_descriptor,
        new java.lang.String[] { "Sku", "ProductName", });
    internal_static_pickingOperations_BinResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pickingOperations_BinResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pickingOperations_BinResponse_descriptor,
        new java.lang.String[] { "Bin", });
    internal_static_pickingOperations_PickRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pickingOperations_PickRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pickingOperations_PickRequest_descriptor,
        new java.lang.String[] { "Bin", "ProductName", "Quantity", });
    internal_static_pickingOperations_PickResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pickingOperations_PickResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pickingOperations_PickResponse_descriptor,
        new java.lang.String[] { "ResultMessage", "PickId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
