// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingOperation.proto

package grpc.smartWarehouse.pickingOperations;

public interface PickResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pickingOperations.PickResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resultMessage = 1;</code>
   */
  java.lang.String getResultMessage();
  /**
   * <code>string resultMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultMessageBytes();

  /**
   * <code>string pickId = 2;</code>
   */
  java.lang.String getPickId();
  /**
   * <code>string pickId = 2;</code>
   */
  com.google.protobuf.ByteString
      getPickIdBytes();
}
