// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingOperation.proto

package grpc.smartWarehouse.pickingOperations;

public interface PickRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pickingOperations.PickRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bin = 1;</code>
   */
  java.lang.String getBin();
  /**
   * <code>string bin = 1;</code>
   */
  com.google.protobuf.ByteString
      getBinBytes();

  /**
   * <code>string productName = 2;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>int32 quantity = 3;</code>
   */
  int getQuantity();
}
