# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pickingService_pb2 as pickingService__pb2


class PickingStub(object):
    """The Picking  service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getBin = channel.unary_unary(
                '/pickingOperations.Picking/getBin',
                request_serializer=pickingService__pb2.BinRequest.SerializeToString,
                response_deserializer=pickingService__pb2.BinResponse.FromString,
                )
        self.pickProduct = channel.unary_unary(
                '/pickingOperations.Picking/pickProduct',
                request_serializer=pickingService__pb2.PickRequest.SerializeToString,
                response_deserializer=pickingService__pb2.PickResponse.FromString,
                )


class PickingServicer(object):
    """The Picking  service definition.
    """

    def getBin(self, request, context):
        """check bin (storage)location number of items by sku(product number)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pickProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PickingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getBin': grpc.unary_unary_rpc_method_handler(
                    servicer.getBin,
                    request_deserializer=pickingService__pb2.BinRequest.FromString,
                    response_serializer=pickingService__pb2.BinResponse.SerializeToString,
            ),
            'pickProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.pickProduct,
                    request_deserializer=pickingService__pb2.PickRequest.FromString,
                    response_serializer=pickingService__pb2.PickResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pickingOperations.Picking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Picking(object):
    """The Picking  service definition.
    """

    @staticmethod
    def getBin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pickingOperations.Picking/getBin',
            pickingService__pb2.BinRequest.SerializeToString,
            pickingService__pb2.BinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pickProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pickingOperations.Picking/pickProduct',
            pickingService__pb2.PickRequest.SerializeToString,
            pickingService__pb2.PickResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
