// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlacingOrderOperation.proto

package OrderOperations;

public interface OrdersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartWarehouse.OrdersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resultMessage = 1;</code>
   */
  java.lang.String getResultMessage();
  /**
   * <code>string resultMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultMessageBytes();

  /**
   * <code>string orderId = 2;</code>
   */
  java.lang.String getOrderId();
  /**
   * <code>string orderId = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
