// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlacingOrderOperation.proto

package OrderOperations;

public final class OrderOperationServiceImpl {
  private OrderOperationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWarehouse_OrdersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWarehouse_OrdersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWarehouse_OrdersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWarehouse_OrdersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWarehouse_Day_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWarehouse_Day_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWarehouse_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWarehouse_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033PlacingOrderOperation.proto\022\016smartWare" +
      "house\"i\n\rOrdersRequest\022\022\n\npersonName\030\001 \001" +
      "(\t\022\017\n\007address\030\002 \001(\t\022\023\n\013productName\030\003 \001(\t" +
      "\022\020\n\010quantity\030\004 \001(\005\022\014\n\004date\030\005 \001(\t\"8\n\016Orde" +
      "rsResponse\022\025\n\rresultMessage\030\001 \001(\t\022\017\n\007ord" +
      "erId\030\002 \001(\t\"\022\n\003Day\022\013\n\003day\030\001 \001(\t\"a\n\005Order\022" +
      "\022\n\npersonName\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\022\023\n\013" +
      "productName\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\005\022\014\n\004d" +
      "ate\030\005 \001(\t2\246\001\n\023PlacingOrderService\022P\n\tget" +
      "Orders\022\035.smartWarehouse.OrdersRequest\032\036." +
      "smartWarehouse.OrdersResponse\"\000(\0010\001\022=\n\013t" +
      "rackOrders\022\023.smartWarehouse.Day\032\025.smartW" +
      "arehouse.Order\"\0000\001B.\n\017OrderOperationsB\031O" +
      "rderOperationServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartWarehouse_OrdersRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartWarehouse_OrdersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWarehouse_OrdersRequest_descriptor,
        new java.lang.String[] { "PersonName", "Address", "ProductName", "Quantity", "Date", });
    internal_static_smartWarehouse_OrdersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartWarehouse_OrdersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWarehouse_OrdersResponse_descriptor,
        new java.lang.String[] { "ResultMessage", "OrderId", });
    internal_static_smartWarehouse_Day_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartWarehouse_Day_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWarehouse_Day_descriptor,
        new java.lang.String[] { "Day", });
    internal_static_smartWarehouse_Order_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartWarehouse_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWarehouse_Order_descriptor,
        new java.lang.String[] { "PersonName", "Address", "ProductName", "Quantity", "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
