// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShippingOperation.proto

package ShippingOperations;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartWarehouse.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string productName = 2;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>bool isPicked = 3;</code>
   */
  boolean getIsPicked();
}
