// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShippingOperation.proto

package ShippingOperations;

public interface ShipmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartWarehouse.Shipment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string productName = 2;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>int32 quantity = 3;</code>
   */
  int getQuantity();

  /**
   * <code>string date = 4;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 4;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
