// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShippingOperation.proto

package ShippingOperations;

public interface ShipResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartWarehouse.ShipResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resultMessage = 1;</code>
   */
  java.lang.String getResultMessage();
  /**
   * <code>string resultMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultMessageBytes();
}
