// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShippingOperation.proto

package ShippingOperations;

public final class ShippingOperationServiceImpl {
  private ShippingOperationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWarehouse_ShipRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWarehouse_ShipRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWarehouse_ShipResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWarehouse_ShipResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWarehouse_Day_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWarehouse_Day_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWarehouse_Shipment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWarehouse_Shipment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ShippingOperation.proto\022\016smartWarehous" +
      "e\"g\n\013ShipRequest\022\022\n\npersonName\030\001 \001(\t\022\017\n\007" +
      "address\030\002 \001(\t\022\023\n\013productName\030\003 \001(\t\022\020\n\010qu" +
      "antity\030\004 \001(\005\022\014\n\004date\030\005 \001(\t\"%\n\014ShipRespon" +
      "se\022\025\n\rresultMessage\030\001 \001(\t\"\022\n\003Day\022\013\n\003day\030" +
      "\001 \001(\t\"P\n\010Shipment\022\017\n\007address\030\001 \001(\t\022\023\n\013pr" +
      "oductName\030\002 \001(\t\022\020\n\010quantity\030\003 \001(\005\022\014\n\004dat" +
      "e\030\004 \001(\t2\243\001\n\017ShippingService\022L\n\013shipProdu" +
      "ct\022\033.smartWarehouse.ShipRequest\032\034.smartW" +
      "arehouse.ShipResponse\"\000(\001\022B\n\rtrackShipme" +
      "nt\022\023.smartWarehouse.Day\032\030.smartWarehouse" +
      ".Shipment\"\0000\001B4\n\022ShippingOperationsB\034Shi" +
      "ppingOperationServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartWarehouse_ShipRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartWarehouse_ShipRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWarehouse_ShipRequest_descriptor,
        new java.lang.String[] { "PersonName", "Address", "ProductName", "Quantity", "Date", });
    internal_static_smartWarehouse_ShipResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartWarehouse_ShipResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWarehouse_ShipResponse_descriptor,
        new java.lang.String[] { "ResultMessage", });
    internal_static_smartWarehouse_Day_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartWarehouse_Day_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWarehouse_Day_descriptor,
        new java.lang.String[] { "Day", });
    internal_static_smartWarehouse_Shipment_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartWarehouse_Shipment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWarehouse_Shipment_descriptor,
        new java.lang.String[] { "Address", "ProductName", "Quantity", "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
