// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShippingOperation.proto

package ShippingOperations;

public interface ShipRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartWarehouse.ShipRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string personName = 1;</code>
   */
  java.lang.String getPersonName();
  /**
   * <code>string personName = 1;</code>
   */
  com.google.protobuf.ByteString
      getPersonNameBytes();

  /**
   * <code>string address = 2;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string productName = 3;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>int32 quantity = 4;</code>
   */
  int getQuantity();

  /**
   * <code>string date = 5;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 5;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
